apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T07:37:27Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2331"
  uid: c9cdbc8d-4da8-4b8e-af66-c8296d99d11b
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.28.199
  clusterIPs:
  - 10.110.28.199
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31862
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
